# CircleCI configuration file
version: 2.1

executors:
  node-executor:
    docker: # exector, docker/window/mac/linux/ubuntu
      - image: cimg/node:20.5.0  

jobs:
  pre-build:
    executor : node-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run: docker build .  
      - run: node --version
  build:
    executor : node-executor
    steps:
      - checkout  
      - run: node --version 
  retake-tests:
    executor : node-executor
    steps:
      - checkout  
      - run: node --version                
      - run:                      # git clone <project-name>
          name: Install npm dependencies
          command: |              # install npm dependencies and install dependencies form package.json
            npm install --save
      - run:
          name: Run unit tests
          command: |              # (./node_modules/mocha/bin/mocha)calling mocha,(test/) look into test folder/  (--reporter mochawesome) create nice html page,and install mochawesome,(reportDir=test-results) genrate report on folder
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  run_tests:
    executor : node-executor
    steps:
      - checkout  
      - run: node --version                
      - run:                      # git clone <project-name>
          name: Install npm dependencies
          command: |              # install npm dependencies and install dependencies form package.json
            npm install --save
      - run:
          name: Run unit tests
          command: |              # (./node_modules/mocha/bin/mocha)calling mocha,(test/) look into test folder/  (--reporter mochawesome) create nice html page,and install mochawesome,(reportDir=test-results) genrate report on folder
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  deploy:
    executor : node-executor
    steps:
      - checkout  
      - run: node --version 
workflows:
  build_test:
    jobs:
      - pre-build
      - build:
          requires:
            - pre-build
      - run_tests:
          requires:
            - build
      - retake-tests:
          requires:
            - build
      - deploy:
          requires:
            - run_tests
            - retake-tests
        