# CircleCI configuration file
version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10  # exector, docker/window/mac/linux/ubuntu
    steps:
      - checkout                  # git clone <project-name>
      - run:
          name: Install npm dependencies
          command: |              # install npm dependencies and install dependencies form package.json
            npm install --save
      - run:
          name: Run unit tests
          command: |              # (./node_modules/mocha/bin/mocha)calling mocha,(test/) look into test folder/  (--reporter mochawesome) create nice html page,and install mochawesome,(reportDir=test-results) genrate report on folder
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build_test:
    jobs:
      - run_tests